cartas_es = {
    #40 CARTAS
    #- OROS -------------------------------------------------------------------------------
    "ES_OR_01":{"literal":"As de Oros"           ,"value":1  ,"priority":1,"realValue":1 },
    "ES_OR_02":{"literal":"Dos de Oros"          ,"value":2  ,"priority":1,"realValue":2 },
    "ES_OR_03":{"literal":"Tres de Oros"         ,"value":3  ,"priority":1,"realValue":3 },
    "ES_OR_04":{"literal":"Quatro de Oros"       ,"value":4  ,"priority":1,"realValue":4 },
    "ES_OR_05":{"literal":"Cinco de Oros"        ,"value":5  ,"priority":1,"realValue":5 },
    "ES_OR_06":{"literal":"Seis de Oros"         ,"value":6  ,"priority":1,"realValue":6 },
    "ES_OR_07":{"literal":"Siete de Oros"        ,"value":7  ,"priority":1,"realValue":7 },
    "ES_OR_08":{"literal":"Sota de Oros"         ,"value":0.5,"priority":1,"realValue":8 },
    "ES_OR_09":{"literal":"Caballo de Oros"      ,"value":0.5,"priority":1,"realValue":9 },
    "ES_OR_10":{"literal":"Rey de Oros"          ,"value":0.5,"priority":1,"realValue":10},
    #- COPAS ------------------------------------------------------------------------------
    "ES_CO_01":{"literal":"As de Copas"          ,"value":1  ,"priority":2,"realValue":1 },
    "ES_CO_02":{"literal":"Dos de Copas"         ,"value":2  ,"priority":2,"realValue":2 },
    "ES_CO_03":{"literal":"Tres de Copas"        ,"value":3  ,"priority":2,"realValue":3 },
    "ES_CO_04":{"literal":"Quatro de Copas"      ,"value":4  ,"priority":2,"realValue":4 },
    "ES_CO_05":{"literal":"Cinco de Copas"       ,"value":5  ,"priority":2,"realValue":5 },
    "ES_CO_06":{"literal":"Seis de Copas"        ,"value":6  ,"priority":2,"realValue":6 },
    "ES_CO_07":{"literal":"Siete de Copas"       ,"value":7  ,"priority":2,"realValue":7 },
    "ES_CO_08":{"literal":"Sota de Copas"        ,"value":0.5,"priority":2,"realValue":8 },
    "ES_CO_09":{"literal":"Caballo de Copas"     ,"value":0.5,"priority":2,"realValue":9 },
    "ES_CO_10":{"literal":"Rey de Copas"         ,"value":0.5,"priority":2,"realValue":10},
    #- ESPADAS ----------------------------------------------------------------------------
    "ES_ES_01":{"literal":"As de Espadas"        ,"value":1  ,"priority":3,"realValue":1 },
    "ES_ES_02":{"literal":"Dos de Espadas"       ,"value":2  ,"priority":3,"realValue":2 },
    "ES_ES_03":{"literal":"Tres de Espadas"      ,"value":3  ,"priority":3,"realValue":3 },
    "ES_ES_04":{"literal":"Quatro de Espadas"    ,"value":4  ,"priority":3,"realValue":4 },
    "ES_ES_05":{"literal":"Cinco de Espadas"     ,"value":5  ,"priority":3,"realValue":5 },
    "ES_ES_06":{"literal":"Seis de Espadas"      ,"value":6  ,"priority":3,"realValue":6 },
    "ES_ES_07":{"literal":"Siete de Espadas"     ,"value":7  ,"priority":3,"realValue":7 },
    "ES_ES_08":{"literal":"Sota de Espadas"      ,"value":0.5,"priority":3,"realValue":8 },
    "ES_ES_09":{"literal":"Caballo de Espadas"   ,"value":0.5,"priority":3,"realValue":9 },
    "ES_ES_10":{"literal":"Rey de Espadas"       ,"value":0.5,"priority":3,"realValue":10},
    #- BASTOS -----------------------------------------------------------------------------
    "ES_BA_01":{"literal":"As de Bastos"         ,"value":1  ,"priority":4,"realValue":1 },
    "ES_BA_02":{"literal":"Dos de Bastos"        ,"value":2  ,"priority":4,"realValue":2 },
    "ES_BA_03":{"literal":"Tres de Bastos"       ,"value":3  ,"priority":4,"realValue":3 },
    "ES_BA_04":{"literal":"Quatro de Bastos"     ,"value":4  ,"priority":4,"realValue":4 },
    "ES_BA_05":{"literal":"Cinco de Bastos"      ,"value":5  ,"priority":4,"realValue":5 },
    "ES_BA_06":{"literal":"Seis de Bastos"       ,"value":6  ,"priority":4,"realValue":6 },
    "ES_BA_07":{"literal":"Siete de Bastos"      ,"value":7  ,"priority":4,"realValue":7 },
    "ES_BA_08":{"literal":"Sota de Bastos"       ,"value":0.5,"priority":4,"realValue":8 },
    "ES_BA_09":{"literal":"Caballo de Bastos"    ,"value":0.5,"priority":4,"realValue":9 },
    "ES_BA_10":{"literal":"Rey de Bastos"        ,"value":0.5,"priority":4,"realValue":10},
}
cartas_en ={
    #52 CARTAS
    #- DIAMANTES --------------------------------------------------------------------------
    "EN_DI_01":{"literal":"As de Diamantes"      ,"value":1  ,"priority":1,"realValue":1 },
    "EN_DI_02":{"literal":"Dos de Diamantes"     ,"value":2  ,"priority":1,"realValue":2 },
    "EN_DI_03":{"literal":"Tres de Diamantes"    ,"value":3  ,"priority":1,"realValue":3 },
    "EN_DI_04":{"literal":"Quatro de Diamantes"  ,"value":4  ,"priority":1,"realValue":4 },
    "EN_DI_05":{"literal":"Cinco de Diamantes"   ,"value":5  ,"priority":1,"realValue":5 },
    "EN_DI_06":{"literal":"Seis de Diamantes"    ,"value":6  ,"priority":1,"realValue":6 },
    "EN_DI_07":{"literal":"Siete de Diamantes"   ,"value":7  ,"priority":1,"realValue":7 },
    "EN_DI_08":{"literal":"Ocho de Diamantes"    ,"value":0.5,"priority":1,"realValue":8 },
    "EN_DI_09":{"literal":"Nueve de Diamantes"   ,"value":0.5,"priority":1,"realValue":9 },
    "EN_DI_10":{"literal":"Diez de Diamantes"    ,"value":0.5,"priority":1,"realValue":10},
    "EN_DI_11":{"literal":"Sota de Diamantes"    ,"value":0.5,"priority":1,"realValue":11},
    "EN_DI_12":{"literal":"Dama de Diamantes"    ,"value":0.5,"priority":1,"realValue":12},
    "EN_DI_13":{"literal":"Rey de Diamantes"     ,"value":0.5,"priority":1,"realValue":13},
    #- CORAZONES --------------------------------------------------------------------------
    "EN_CO_01":{"literal":"As de Corazones"      ,"value":1  ,"priority":2,"realValue":1 },
    "EN_CO_02":{"literal":"Dos de Corazones"     ,"value":2  ,"priority":2,"realValue":2 },
    "EN_CO_03":{"literal":"Tres de Corazones"    ,"value":3  ,"priority":2,"realValue":3 },
    "EN_CO_04":{"literal":"Quatro de Corazones"  ,"value":4  ,"priority":2,"realValue":4 },
    "EN_CO_05":{"literal":"Cinco de Corazones"   ,"value":5  ,"priority":2,"realValue":5 },
    "EN_CO_06":{"literal":"Seis de Corazones"    ,"value":6  ,"priority":2,"realValue":6 },
    "EN_CO_07":{"literal":"Siete de Corazones"   ,"value":7  ,"priority":2,"realValue":7 },
    "EN_CO_08":{"literal":"Ocho de Corazones"    ,"value":0.5,"priority":2,"realValue":8 },
    "EN_CO_09":{"literal":"Nueve de Corazones"   ,"value":0.5,"priority":2,"realValue":9 },
    "EN_CO_10":{"literal":"Diez de Corazones"    ,"value":0.5,"priority":2,"realValue":10},
    "EN_CO_11":{"literal":"Sota de Corazones"    ,"value":0.5,"priority":2,"realValue":11},
    "EN_CO_12":{"literal":"Dama de Corazones"    ,"value":0.5,"priority":2,"realValue":12},
    "EN_CO_13":{"literal":"Rey de Corazones"     ,"value":0.5,"priority":2,"realValue":13},
    #- PICAS ------------------------------------------------------------------------------
    "EN_PI_01":{"literal":"As de Picas"          ,"value":1  ,"priority":3,"realValue":1 },
    "EN_PI_02":{"literal":"Dos de Picas"         ,"value":2  ,"priority":3,"realValue":2 },
    "EN_PI_03":{"literal":"Tres de Picas"        ,"value":3  ,"priority":3,"realValue":3 },
    "EN_PI_04":{"literal":"Quatro de Picas"      ,"value":4  ,"priority":3,"realValue":4 },
    "EN_PI_05":{"literal":"Cinco de Picas"       ,"value":5  ,"priority":3,"realValue":5 },
    "EN_PI_06":{"literal":"Seis de Picas"        ,"value":6  ,"priority":3,"realValue":6 },
    "EN_PI_07":{"literal":"Siete de Picas"       ,"value":7  ,"priority":3,"realValue":7 },
    "EN_PI_08":{"literal":"Ocho de Picas"        ,"value":0.5,"priority":3,"realValue":8 },
    "EN_PI_09":{"literal":"Nueve de Picas"       ,"value":0.5,"priority":3,"realValue":9 },
    "EN_PI_10":{"literal":"Diez de Picas"        ,"value":0.5,"priority":3,"realValue":10},
    "EN_PI_11":{"literal":"Sota de Picas"        ,"value":0.5,"priority":3,"realValue":11},
    "EN_PI_12":{"literal":"Dama de Picas"        ,"value":0.5,"priority":3,"realValue":12},
    "EN_PI_13":{"literal":"Rey de Picas"         ,"value":0.5,"priority":3,"realValue":13},
    #- TRÉBOLES ---------------------------------------------------------------------------
    "EN_TR_01":{"literal":"As de Tréboles"       ,"value":1  ,"priority":4,"realValue":1 },
    "EN_TR_02":{"literal":"Dos de Tréboles"      ,"value":2  ,"priority":4,"realValue":2 },
    "EN_TR_03":{"literal":"Tres de Tréboles"     ,"value":3  ,"priority":4,"realValue":3 },
    "EN_TR_04":{"literal":"Quatro de Tréboles"   ,"value":4  ,"priority":4,"realValue":4 },
    "EN_TR_05":{"literal":"Cinco de Tréboles"    ,"value":5  ,"priority":4,"realValue":5 },
    "EN_TR_06":{"literal":"Seis de Tréboles"     ,"value":6  ,"priority":4,"realValue":6 },
    "EN_TR_07":{"literal":"Siete de Tréboles"    ,"value":7  ,"priority":4,"realValue":7 },
    "EN_TR_08":{"literal":"Ocho de Tréboles"     ,"value":0.5,"priority":4,"realValue":8 },
    "EN_TR_09":{"literal":"Nueve de Tréboles"    ,"value":0.5,"priority":4,"realValue":9 },
    "EN_TR_10":{"literal":"Diez de Tréboles"     ,"value":0.5,"priority":4,"realValue":10},
    "EN_TR_11":{"literal":"Sota de Tréboles"     ,"value":0.5,"priority":4,"realValue":11},
    "EN_TR_12":{"literal":"Dama de Tréboles"     ,"value":0.5,"priority":4,"realValue":12},
    "EN_TR_13":{"literal":"Rey de Tréboles"      ,"value":0.5,"priority":4,"realValue":13},
}
cartas_al = {
    #60 CARTAS
    #- CAMPANAS ---------------------------------------------------------------------------
    "AL_CA_01":{"literal":"As de Campanas"       ,"value":1  ,"priority":1,"realValue":1 },
    "AL_CA_02":{"literal":"Dos de Campanas"      ,"value":2  ,"priority":1,"realValue":2 },
    "AL_CA_03":{"literal":"Tres de Campanas"     ,"value":3  ,"priority":1,"realValue":3 },
    "AL_CA_04":{"literal":"Quatro de Campanas"   ,"value":4  ,"priority":1,"realValue":4 },
    "AL_CA_05":{"literal":"Cinco de Campanas"    ,"value":5  ,"priority":1,"realValue":5 },
    "AL_CA_06":{"literal":"Seis de Campanas"     ,"value":6  ,"priority":1,"realValue":6 },
    "AL_CA_07":{"literal":"Siete de Campanas"    ,"value":7  ,"priority":1,"realValue":7 },
    "AL_CA_08":{"literal":"Ocho de Campanas"     ,"value":0.5,"priority":1,"realValue":8 },
    "AL_CA_09":{"literal":"Nueve de Campanas"    ,"value":0.5,"priority":1,"realValue":9 },
    "AL_CA_10":{"literal":"Diez de Campanas"     ,"value":0.5,"priority":1,"realValue":10},
    "AL_CA_11":{"literal":"Inferior de Campanas" ,"value":0.5,"priority":1,"realValue":11},
    "AL_CA_12":{"literal":"Superior de Campanas" ,"value":0.5,"priority":1,"realValue":12},
    "AL_CA_13":{"literal":"Rey de Campanas"      ,"value":0.5,"priority":1,"realValue":13},
    "AL_CA_14":{"literal":"Verano"               ,"value":0.5,"priority":1,"realValue":14},
    "AL_CA_15":{"literal":"Fuego"                ,"value":0.5,"priority":1,"realValue":15},
    #- CORAZONES --------------------------------------------------------------------------
    "AL_CO_01":{"literal":"As de Corazones"      ,"value":1  ,"priority":2,"realValue":1 },
    "AL_CO_02":{"literal":"Dos de Corazones"     ,"value":2  ,"priority":2,"realValue":2 },
    "AL_CO_03":{"literal":"Tres de Corazones"    ,"value":3  ,"priority":2,"realValue":3 },
    "AL_CO_04":{"literal":"Quatro de Corazones"  ,"value":4  ,"priority":2,"realValue":4 },
    "AL_CO_05":{"literal":"Cinco de Corazones"   ,"value":5  ,"priority":2,"realValue":5 },
    "AL_CO_06":{"literal":"Seis de Corazones"    ,"value":6  ,"priority":2,"realValue":6 },
    "AL_CO_07":{"literal":"Siete de Corazones"   ,"value":7  ,"priority":2,"realValue":7 },
    "AL_CO_08":{"literal":"Ocho de Corazones"    ,"value":0.5,"priority":2,"realValue":8 },
    "AL_CO_09":{"literal":"Nueve de Corazones"   ,"value":0.5,"priority":2,"realValue":9 },
    "AL_CO_10":{"literal":"Diez de Corazones"    ,"value":0.5,"priority":2,"realValue":10},
    "AL_CO_11":{"literal":"Inferior de Corazones","value":0.5,"priority":2,"realValue":11},
    "AL_CO_12":{"literal":"Superior de Corazones","value":0.5,"priority":2,"realValue":12},
    "AL_CO_13":{"literal":"Rey de Corazones"     ,"value":0.5,"priority":2,"realValue":13},
    "AL_CO_14":{"literal":"Primavera"            ,"value":0.5,"priority":2,"realValue":14},
    "AL_CO_15":{"literal":"Tierra"               ,"value":0.5,"priority":2,"realValue":15},
    #- HOJAS ------------------------------------------------------------------------------
    "AL_HO_01":{"literal":"As de Hojas"          ,"value":1  ,"priority":3,"realValue":1 },
    "AL_HO_02":{"literal":"Dos de Hojas"         ,"value":2  ,"priority":3,"realValue":2 },
    "AL_HO_03":{"literal":"Tres de Hojas"        ,"value":3  ,"priority":3,"realValue":3 },
    "AL_HO_04":{"literal":"Quatro de Hojas"      ,"value":4  ,"priority":3,"realValue":4 },
    "AL_HO_05":{"literal":"Cinco de Hojas"       ,"value":5  ,"priority":3,"realValue":5 },
    "AL_HO_06":{"literal":"Seis de Hojas"        ,"value":6  ,"priority":3,"realValue":6 },
    "AL_HO_07":{"literal":"Siete de Hojas"       ,"value":7  ,"priority":3,"realValue":7 },
    "AL_HO_08":{"literal":"Ocho de Hojas"        ,"value":0.5,"priority":3,"realValue":8 },
    "AL_HO_09":{"literal":"Nueve de Hojas"       ,"value":0.5,"priority":3,"realValue":9 },
    "AL_HO_10":{"literal":"Diez de Hojas"        ,"value":0.5,"priority":3,"realValue":10},
    "AL_HO_11":{"literal":"Inferior de Hojas"    ,"value":0.5,"priority":3,"realValue":11},
    "AL_HO_12":{"literal":"Superior de Hojas"    ,"value":0.5,"priority":3,"realValue":12},
    "AL_HO_13":{"literal":"Rey de Hojas"         ,"value":0.5,"priority":3,"realValue":13},
    "AL_HO_14":{"literal":"Otoño"                ,"value":0.5,"priority":3,"realValue":14},
    "AL_HO_15":{"literal":"Aire"                 ,"value":0.5,"priority":3,"realValue":15},
    #- BELLOTAS ---------------------------------------------------------------------------
    "AL_BE_01":{"literal":"As de Bellotas"       ,"value":1  ,"priority":4,"realValue":1 },
    "AL_BE_02":{"literal":"Dos de Bellotas"      ,"value":2  ,"priority":4,"realValue":2 },
    "AL_BE_03":{"literal":"Tres de Bellotas"     ,"value":3  ,"priority":4,"realValue":3 },
    "AL_BE_04":{"literal":"Quatro de Bellotas"   ,"value":4  ,"priority":4,"realValue":4 },
    "AL_BE_05":{"literal":"Cinco de Bellotas"    ,"value":5  ,"priority":4,"realValue":5 },
    "AL_BE_06":{"literal":"Seis de Bellotas"     ,"value":6  ,"priority":4,"realValue":6 },
    "AL_BE_07":{"literal":"Siete de Bellotas"    ,"value":7  ,"priority":4,"realValue":7 },
    "AL_BE_08":{"literal":"Ocho de Bellotas"     ,"value":0.5,"priority":4,"realValue":8 },
    "AL_BE_09":{"literal":"Nueve de Bellotas"    ,"value":0.5,"priority":4,"realValue":9 },
    "AL_BE_10":{"literal":"Diez de Bellotas"     ,"value":0.5,"priority":4,"realValue":10},
    "AL_BE_11":{"literal":"Inferior de Bellotas" ,"value":0.5,"priority":4,"realValue":11},
    "AL_BE_12":{"literal":"Superior de Bellotas" ,"value":0.5,"priority":4,"realValue":12},
    "AL_BE_13":{"literal":"Rey de Bellotas"      ,"value":0.5,"priority":4,"realValue":13},
    "AL_BE_14":{"literal":"Invierno"             ,"value":0.5,"priority":4,"realValue":14},
    "AL_BE_15":{"literal":"Agua"                 ,"value":0.5,"priority":4,"realValue":15},
}

context_game = {
    "cards_deck":{}, #Baraja de cartas seleccionada
    "mazo":[],       #Mazo de carta de la partida
    
    "players":{        
        "11115555A":{
            "name":"Mario",
            "human":True,
            "bank":False,
            "initialCard":"",
            "priority":0,
            "type":40,
            "bet":4,
            "points":0,
            "cards":[],
            "roundPoints":0
        },
        "22225555A":{
            "name":"Pepe",
            "human":False,
            "bank":False,
            "initialCard":"",
            "priority":0,
            "type":30,
            "bet":4,
            "points":0,
            "cards":[],
            "roundPoints":0
        },
        "33335555A":{
            "name":"Jose1",
            "human":False,
            "bank":False,
            "initialCard":"",
            "priority":0,
            "type":50,
            "bet":4,
            "points":0,
            "cards":[],
            "roundPoints":0
        },
        "44445555A":{
            "name":"Jose2",
            "human":False,
            "bank":False,
            "initialCard":"",
            "priority":0,
            "type":50,
            "bet":4,
            "points":0,
            "cards":[],
            "roundPoints":0
        },
        "55555555A":{
            "name":"Jose3",
            "human":False,
            "bank":False,
            "initialCard":"",
            "priority":0,
            "type":50,
            "bet":4,
            "points":0,
            "cards":[],
            "roundPoints":0
        },        
        "66665555A":{
            "name":"Jose4",
            "human":False,
            "bank":False,
            "initialCard":"",
            "priority":0,
            "type":50,
            "bet":4,
            "points":0,
            "cards":[],
            "roundPoints":0
        },
        "77775555A":{
            "name":"Jose5",
            "human":False,
            "bank":False,
            "initialCard":"",
            "priority":0,
            "type":50,
            "bet":4,
            "points":0,
            "cards":[],
            "roundPoints":0
        },
    },    #Jugadores extraidos de la base de datos
    "game":[],       #Jugadores en partida

    "round":0,      #Ronda actual
    "maxRounds":5,   #Rondas maximas de la partida
    "round_history":[]
}